### ISSUE TITLE
Unable to center cover video 

### ISSUE THREAD

**Issue by vivianzqq** [ShareVR/ShareVR-WebsiteDev#10]
The cover video is not centered if I maximize the window. Not sure why. I suspect we need to change the dimensions of the video file. 

Also, I want to make the cover video smaller, like what we have now on the live site. If it's smaller, people  will see the four icons underneath directly and they don't need to scroll down. 

The problem I have is I'm not sure I can solve these two problems at the same time by changing the dimensions of the video (I also don't know how to change them honestly...).

**Comment by adammy123** [comment]
@vivianzqq I have taken some time to look at this issue and here are my suggestions:

1. From the template that you adapted the website from, it seems that the header background uses a jpg file. I have tried using a gif file and it worked, however, I used a free online tool to convert the cover-video.mp4 file to a .gif file. This has caused a drop in frame rate and the ratio to have changed slightly, so you may want to source for a better mp4 to gif converter. (this may be useful if we want to preserve the adapted template, and also since we are not playing any sounds, a gif might work better)
2. The video itself seems a little long to be on the header - would a visitor of the site stay in the header section of the website for 40 seconds?
3. The title and tagline of the headers also may block the content of the video, especially the part when the Facebook profile is shown.
4. The video(and the parts between the sign-up button and the contact page) is not mobile-friendly and flexible screen size friendly. What I mean is that the video will be cropped depending on the user's screen size. This may not be a problem for most parts of the video as the sides and bottom of the content is not that important. However, the comments of the Facebook page is at the bottom of the video, which may be cropped out.

**Comment by hwkeyser** [comment]
Solved the video center issue in my latest pull request, #12, This does not solve issues with video length or content, but solves the not-centered issue. The video should now be centered regardless of screen width. (but it does not scale the video).

**Comment by hwkeyser** [comment]
Please note, a lot of what you guys have listed above are multiple issues. I'm going to separate the above that were not solved into individual issues, and then close this one.
